Auto-detect active partition number instead of assuming it is 1.

diff --git a/trunk/unattended/linuxboot/misc/master b/trunk/unattended/linuxboot/misc/master
--- a/trunk/unattended/linuxboot/misc/master
+++ b/trunk/unattended/linuxboot/misc/master
@@ -344,11 +344,26 @@ export Z_PATH Z_USER Z_PASS
 # Used as staging area by install.pl
 mkdir /c
 
-if perl -I/z/lib /z/dosbin/install.pl ; then
-    # Always exits non-zero.  FIXME.
-    dosemu.bin
-    sync
-    reboot
+perl -I/z/lib /z/dosbin/install.pl \
+    || die "install.pl exited non-zero"
+
+# Determine partition number to use.
+active_part_line=`parted /dev/dsk print | grep '^[[:digit:]].*[[:space:]]boot'`
+active_part=${active_part_line%% *}
+
+if [ -z "$active_part" ] ; then
+    echo "Partition table:" >&2
+    parted /dev/dsk print >&2
+    die "No active partition found!"
 fi
+
+cp /etc/dosemu/dosemu.conf /tmp
+echo \$_hdimage = \"/dev/dsk$active_part\" >> /tmp/dosemu.conf
+
+# DOSEMU always exits non-zero.  FIXME.
+dosemu.bin -f /tmp/dosemu.conf
+
+sync
+reboot
 
 exec bash
