First attempt to support I2O devices (some guesswork here).

diff --git a/unattended/linuxboot/misc/make-blkdev-nodes b/unattended/linuxboot/misc/make-blkdev-nodes
--- a/unattended/linuxboot/misc/make-blkdev-nodes
+++ b/unattended/linuxboot/misc/make-blkdev-nodes
@@ -10,25 +10,36 @@ sys_block=/sys/block
 [ -d $sys_block ] \
     || die "$sys_block not found!"
 
-# Argument is a directory like /sys/block/hda or /sys/block/sda/sda3
+# Argument is a directory like /sys/block/hda, /sys/block/sda/sda1,
+# /sys/block/i2o!hda, or /sys/block/i2o!hda/i2o!hda2.
 make_block_device () {
     local path="$1"
 
+    # Everything after the last /
     local name=${path##*/}
-    local fullname="/dev/$name"
-    echo "Making device $fullname"
+    local dev_file="/dev/$name"
+    # Replace ! with /
+    dev_file=${dev_file//\!/\/}
+    echo "Making device $dev_file"
     [ -f "$path/dev" ] \
-        || die "Internal error: $path/dev not found"
+        || die "$0: Internal error: $path/dev not found"
+
+    # Everything up to the last /
+    local dev_dir=${dev_file%/*}
+    mkdir -p "$dev_dir"
+    [ -d "$dev_dir" ] \
+        || die "$0: Unable to mkdir $dev_dir"
 
     local major_minor="`cat $path/dev`"
-    local temp="$fullname.$$.tmp"
+    local temp="$dev_file.$$.tmp"
     mknod "$temp" b ${major_minor%:*} ${major_minor#*:} \
         || die "mknod failed"
-    mv -f "$temp" "$fullname" \
+    mv -f "$temp" "$dev_file" \
         || die "rename $temp to $fullname failed"
 }
 
-dev="$1"
+# Replace / with !
+dev="${1//\//\!}"
 
 [ -n "$dev" ] \
     || die "$0: I need an argument"
