Use alternative instalation process. Thanks to Nils Olav Fossum and Mario Gzuk
git-svn-id: https://svn.code.sf.net/p/unattended/code/trunk@2747 3671eaaa-a6c4-423f-a734-8bc38373c25a

diff --git a/unattended/linuxboot/misc/master b/unattended/linuxboot/misc/master
--- a/unattended/linuxboot/misc/master
+++ b/unattended/linuxboot/misc/master
@@ -363,14 +363,6 @@ fi
 
 echo "*** By Jove, I think we've got it!"
 
-# FIXME: Bad hack to work around dosemu bug running over network
-rm /usr/bin/dosemu.bin
-cp /z/linuxaux/usr/bin/dosemu.bin /usr/bin/dosemu.bin
-rm -f /var/lib /var/lib/dosemu /var/lib/dosemu/drives \
-    /var/lib/dosemu/drives/dosboot.img >/dev/null 2>&1
-mkdir -p /var/lib/dosemu/drives
-cp /z/linuxaux/var/lib/dosemu/drives/dosboot.img /var/lib/dosemu/drives/.
-
 # install.pl relies on these environment variables
 # (see also LEGACY_BIOS_HEAD and LEGACY_BIOS_SECT above)
 export Z_PATH Z_USER Z_PASS
@@ -391,13 +383,70 @@ if [ -z "$active_part" ] ; then
     die "No active partition found!"
 fi
 
-cp /etc/dosemu/dosemu.conf /tmp
-echo \$_hdimage = \"/dev/dsk$active_part\" >> /tmp/dosemu.conf
+#load functions so we can parse /c/netinst/unattend.txt:
+[ -f /usr/lib/unatt-functions.sh ] || die "/usr/lib/unatt-functions.sh not found" 
+. /usr/lib/unatt-functions.sh
 
-# DOSEMU always exits non-zero.  FIXME.
-dosemu.bin -f /tmp/dosemu.conf
+ntinstall_cmd=`parse_ini_file /c/netinst/unattend.txt _meta ntinstall_cmd`
+
+if [ -z "$ntinstall_cmd" ]
+then  
+    #Run the orginal dosemu:
+
+    # FIXME: Bad hack to work around dosemu bug running over network
+    rm /usr/bin/dosemu.bin
+    cp /z/linuxaux/usr/bin/dosemu.bin /usr/bin/dosemu.bin
+    rm -f /var/lib /var/lib/dosemu /var/lib/dosemu/drives \
+       /var/lib/dosemu/drives/dosboot.img >/dev/null 2>&1
+    mkdir -p /var/lib/dosemu/drives
+    cp /z/linuxaux/var/lib/dosemu/drives/dosboot.img /var/lib/dosemu/drives/.
+
+    cp /etc/dosemu/dosemu.conf /tmp
+    echo \$_hdimage = \"/dev/dsk$active_part\" >> /tmp/dosemu.conf
+
+    # DOSEMU always exits non-zero.  FIXME.
+    dosemu.bin -f /tmp/dosemu.conf
+
+    #lets see if we should fix partition geometry - to avoid 'ntldr not found'
+    fix_disk_geo_heads=`parse_ini_file /c/netinst/unattend.txt _meta fix_disk_geo_heads`
+    fix_disk_geo_sectors=`parse_ini_file /c/netinst/unattend.txt _meta fix_disk_geo_sectors`
+    if [ -n "$fix_disk_geo_heads" ] && [ -n "$fix_disk_geo_heads" ] ; then
+        echo "fixing disk geometry .."
+        echo -e -n "\x`printf "%02X" $fix_disk_geo_heads`"|dd of=/dev/dsk$active_part bs=1 seek=26 conv=notrunc
+        echo -e -n "\x`printf "%02X" $fix_disk_geo_sectors`"|dd of=/dev/dsk$active_part bs=1 seek=24 conv=notrunc
+        echo "..done"
+    fi
+
+    echo "mount /c, we might still do some adjustments. It better be mountable now."
+    mount -t vfat /dev/dsk$active_part /c || die "Could not mount /c"
+
+    if [ -n "$fix_disk_geo_heads" ] && [ -n "$fix_disk_geo_heads" ] ; then
+        # We also need to fix disk geometry in bootsect.dat
+        bootsectfile="/c/\$win_nt\$.~bt/bootsect.dat"
+        [ -f "$bootsectfile" ] || die "$bootsectfile not found"
+        echo "fixing disk geometry in $bootsectfile .."
+        echo -e -n "\x`printf "%02X" $fix_disk_geo_heads`"|dd of=$bootsectfile bs=1 seek=26 conv=notrunc
+	echo -e -n "\x`printf "%02X" $fix_disk_geo_sectors`"|dd of=$bootsectfile bs=1 seek=24 conv=notrunc
+        echo "..done"
+    fi
+else
+    echo -e "* Running ntinstall_cmd: $ntinstall_cmd"
+    $ntinstall_cmd || die "* $ntinstall_cmd exited non-zero"
+fi
+
+# Installation is now complete, /c is mounted, some adjustments (if any) follows..
+
+post_ntinstall_cmd=`parse_ini_file /c/netinst/unattend.txt _meta post_ntinstall_cmd`
+if [ -n "$post_ntinstall_cmd" ] ; then
+    echo -e "* Running post_ntinstall_cmd: $post_ntinstall_cmd"
+    $post_ntinstall_cmd || die "* $post_ntinstall_cmd exited non-zero"
+fi
 
 sync
+umount /c
+
+echo "all done!"
+
 reboot
 
 exec bash
